language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      before_script:
        - wget http://131.123.42.38/lmcrs/beta/srcML-Ubuntu18.04.deb && sudo apt install ./srcML-Ubuntu18.04.deb
        - srcml --version
        - echo "TESTS := '~[srcml095-broken]'" > config.mk
    - os: linux
      compiler: clang
      dist: bionic
      before_script:
        - wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu18.04.deb && sudo apt install ./srcml_1.0.0-1_ubuntu18.04.deb
        - srcml --version
        - echo "TESTS := '*'" > config.mk
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      before_script:
        - export PATH="/usr/local/opt/bison/bin:$PATH"
      addons:
        homebrew:
          update: true
          packages:
            - bison

addons:
  apt:
    packages:
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libarchive13

script:
  - make -j4
  - make -j4 check

notifications:
  email:
    recipients:
      - xaizek@posteo.net
